name: Daily Exchange Rates Update

on:
  schedule:
    - cron: '0 0 * * *'
    #- cron: '0 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4 # 최신 v4 권장
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 라이브러리 설치
        run: |
          pip install requests pandas python-dotenv pymysql lxml

      - name: 환율 스크립트 실행
        env:
          EXCHANGE_KEY: ${{ secrets.EXCHANGE_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          python fetch_rates/fetch_rates.py

      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add data/exchange_rates.csv data/naver_exchange.html logs/execution.log
          git commit -m "Update exchange rates [$(date)]" || exit 0
          
          # UI에서 막혀있을 때를 대비해 명시적 푸시
          git push origin HEAD:${{ github.ref }}